"""updated food column name from img->image

Revision ID: 2c5f0c3fdd09
Revises: c7d7e86c42f0
Create Date: 2026-04-14 17:24:18.755946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5f0c3fdd09'
down_revision: Union[str, Sequence[str], None] = 'c7d7e86c42f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('image', sa.String(), nullable=False))
    op.drop_column('foods', 'img')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('foods', 'image')
    # ### end Alembic commands ###
