"""updated carts column name from qty->quantity

Revision ID: 786eb8122483
Revises: 9cd88973205a
Create Date: 2026-04-15 10:12:58.093946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786eb8122483'
down_revision: Union[str, Sequence[str], None] = '9cd88973205a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_column('carts', 'qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('carts', 'quantity')
    # ### end Alembic commands ###
