"""sync user model columns

Revision ID: c7d7e86c42f0
Revises: 349fa8949021
Create Date: 2026-04-14 16:02:04.888967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d7e86c42f0'
down_revision: Union[str, Sequence[str], None] = '349fa8949021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
